### ISSUE TITLE
Scoped Methods

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#69]
Hi Yuri,

i updated to the rails 3.1 and where i'm using wicegrid this issue appear: 

NoMethodError in CentrosDeCustoController#index 

undefined method `scoped_methods' for #ActiveRecord::Relation:0xb75f9e4

The code in my controller:  
@centros_de_custo_grid = initialize_grid(CentroDeCusto.where("empresa_loja_id = ?", session[:loja_corrente]) )

In rails 3.0.10 it's OK!

Can you give me some help ? 

Thnks for attention

**Comment by leikind** [comment]
What's the version of the plugin?

**Comment by fillipenorton** [comment]
Well, 

I was using an old version an just updated to 3.0.4 and it's running OK.

By the way, this version have some support for datetime inputs ?

Really thanks for your attention.

**Comment by leikind** [comment]
You use jQuery, I suppose? By default DATETIME fields get the ugly Rails datetime dropdown helpers.

There is a new version under development targeting Rails 3.2 and the asset pipeline (but should probably also work with 3.1) with a lot of cleanups, rewritten in many places, there both DATE and DATETIME columns will get jQuery Datepicker by default, with a possibility to revert to the Rails helpers. It will also be easier to add your own filters, so if someone wants to write a filter for a Datetime column, it'll be possible.

If you feel adventurous I can say what lines to hack to get jQuery Datepicker for DATETIME in your version. I hope to release a usable RC gem by the end of May-beginning of June latest
